### ISSUE TITLE
Syntax error halts validation of other files and prints backtrace

### ISSUE THREAD

**Issue by FWest98** [python-jsonschema/check-jsonschema#141]
I am trying to implement check-jsonschema in our workflow, where we intend to use it as a git hook that will automatically validate all relevant files. Unfortunately, once one of the files has a syntax error (that will cause a `JSONDecodeError`), the entire checking process halts and no other files are validated. In addition, an entire stacktrace is printed.

This feels a bit user-unfriendly and makes the output of this tool less useful. I am not sure whether this is intended behaviour; but I would like to see the invalid file being skipped (with an error printed), without causing the entire program to crash. This does in fact seem to be the behaviour of the old CLI `jsonschema`.

Would it be possible to look into this?

**Comment by sirosen** [comment]
That sounds like a reasonable use-case and a good improvement to the behavior! Consider this "accepted" -- I'll try to find time to work on this.

**Comment by sirosen** [comment]
I've just released v0.18.0, which changes the way that parsing errors are handled to accommodate this.
The error output has changed slightly, and it should no longer stop processing when a file fails to parse.

I hope this works well for you. Let me know if you run into issues with it!

**Comment by FWest98** [comment]
Thank you so much! It works very well for JSON, but invalid YAML files still crash the tool, unfortunately. They crash with a `ScannerError`, which seems like is not being caught in the code yet.

**Comment by sirosen** [comment]
Can you provide me with a sample YAML file which crashes things in this way? I tested against YAML and other formats, so it's _supposed_ to work, but I guess I'm missing some case(s).

**Comment by FWest98** [comment]
For example:
```yaml
foo: bar
invalid
```

**Comment by sirosen** [comment]
Thanks for the example! I'm able to reproduce and I see the cause.

The current code catches `ruamel.yaml.ParserError`, but that only refers to errors during the parse phase of YAML loading. The above produces a `ScannerError` (IIRC "scanning" is tokenization/lexing).
I should probably broaden the error class to the base `YAMLError`. I expect to have a fix done, tested, and released within the next couple of hours.

**Comment by sirosen** [comment]
Sorry, did I say the next couple of hours? I meant minutes! 😅 
(The fix and testing for it came together surprisingly easily.)

v0.18.2 is now available with the fix. Please give it a go and let me know if it still isn't working for any reason!

**Comment by FWest98** [comment]
Works perfectly fine! Thanks so much for the quick replies, this is the most usable tool of all yaml/json linters/checkers for use in a git hook.
